### ISSUE TITLE
Can't make eboard on Ubuntu undefined reference to "Gtk Widgets"

### ISSUE THREAD

**Issue by bretantonio** [fbergo/eboard#8] opened 2018-10-29 12:24 UTC
make gets errors Ubuntu Bionic 64 bit

The step which gives an error is 
`g++ -lpthread -ldl -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lfontconfig -lfreetype -lpng16 -lz -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0 -o eboard board.o bugpane.o chess.o cimg.o clock.o dgtboard.o dlg_connect.o dlg_gamelist.o dlg_prefs.o global.o help.o history.o main.o mainwindow.o movelist.o network.o notebook.o ntext.o p2p.o pieces.o position.o promote.o proto_fics.o proto_p2p.o proto_xboard.o protocol.o quickbar.o script.o seekgraph.o sound.o status.o text.o tstring.o util.o widgetproxy.o langs.o
Makefile:45: recipe for target 'eboard' failed`

It leads to errors like 
`position.o: In function `Position::moveAnyNotation(char const*, short, variant)':
position.cc:(.text+0x6651): undefined reference to `g_strlcpy'
proto_xboard.o: In function `XBoardProtocol::setupPosition()':
proto_xboard.cc:(.text+0x49a): undefined reference to `g_strlcpy'
proto_xboard.o: In function `XBoardProtocol::createDialog()':
proto_xboard.cc:(.text+0x52a): undefined reference to `gtk_window_new'
proto_xboard.cc:(.text+0x542): undefined reference to `gtk_window_get_type'
proto_xboard.cc:(.text+0x551): undefined reference to `g_type_check_instance_cast'
proto_xboard.cc:(.text+0x55c): undefined reference to `gtk_window_set_title'
proto_xboard.cc:(.text+0x568): undefined reference to `g_type_check_instance_cast'
proto_xboard.cc:(.text+0x575): undefined reference to `gtk_window_set_position'
proto_xboard.cc:(.text+0x57a): undefined reference to `gtk_container_get_type'
proto_xboard.cc:(.text+0x589): undefined reference to `g_type_check_instance_cast'
proto_xboard.cc:(.text+0x596): undefined reference to `gtk_container_set_border_width'
proto_xboard.cc:(.text+0x59f): undefined reference to `gtk_widget_realize'
proto_xboard.cc:(.text+0x5a8): undefined reference to `gtk_vbox_new'
proto_xboard.cc:(.text+0x5b7): undefined reference to `g_type_check_instance_cast'
proto_xboard.cc:(.text+0x5c2): undefined reference to `gtk_container_add'
proto_xboard.cc:(.text+0x5c7): undefined reference to `gtk_notebook_new'
proto_xboard.cc:(.text+0x5d3): undefined reference to `gtk_box_get_type'`

**Comment by fbergo** [comment] 2018-10-30 20:13
I have committed a tentative fix for this, but I am unable to test as the issue is not reproducible in my build systems. ( for future reference, it seems to be related to the order of compiler arguments when linking, https://ubuntuforums.org/showthread.php?t=2074887 )

**Closed as completed by fbergo** 2018-10-30 20:13 UTC

**Comment by bretantonio** [comment] 2018-10-31 13:19
Fixed thanks
